language: python
email:
    recipients:
      - OMC-team@cern.ch
      - efol@cern.ch
    on_success: always
    on_failure: always
python:
 - "2.7"
env:
 - EXCITATION=--acd
 - EXCITATION=--adt 
 - EXCITATION= 
script:
 - travis_wait 30 ./runTests.sh
